#! /bin/bash

# feature selection based on j48 tree classifier

jvm_mem=2g
weka_jar=/home/rcf-proj/mv/guptarah/interspeech_ch/scripts/weka-3-6-6/weka.jar
C=0.1

rm -r psy_only_results
mkdir psy_only_results
mkdir psy_only_results/all_task

for dirs in ../feature_selection/psy_features/*
do
	echo $(basename $dirs)
	mkdir psy_only_results/all_task/$(basename $dirs)
	save_dir=psy_only_results/all_task/$(basename $dirs)	

	train_file_cur=$save_dir/train_file.arff
	test_file_cur=$save_dir/test_file.arff
	model_file=$save_dir/model.$C
	prediction_file=$save_dir/prediction

	train_file_sel=$save_dir/train_file.sel.arff
	test_file_sel=$save_dir/test_file.sel.arff

	train_file=$dirs/train_file.arff
	test_file=$dirs/test_file.arff

	train_file_ds=$dirs/train_file.ds.arff
	
	# make the training file after removing task id
	java -Xmx$jvm_mem -classpath $weka_jar weka.filters.unsupervised.attribute.Remove -R 1 -b -i $train_file -o $train_file_cur -r $test_file -s $test_file_cur

	######################
	# do feature selection	
	######################

	# using CfsSubsetEval
	java -Xmx$jvm_mem -classpath $weka_jar weka.filters.supervised.attribute.AttributeSelection -E "weka.attributeSelection.CfsSubsetEval -M"  -S "weka.attributeSelection.BestFirst -D 1 -N 10 -P 1" -b -i $train_file -o $train_file_sel -r $test_file -s $test_file_sel

	# using one R classifier
	# java -Xmx$jvm_mem -classpath $weka_jar weka.filters.supervised.attribute.AttributeSelection -E "weka.attributeSelection.OneRAttributeEval -D"  -S "weka.attributeSelection.Ranker -N 15 -P 1" -b -i $train_file -o $train_file_sel -r $test_file -s $test_file_sel

	####################################
	# train and test on all the features
	####################################

	# svm classifier
	java -Xmx$jvm_mem -classpath $weka_jar weka.classifiers.meta.FilteredClassifier -v -o -no-cv -t $train_file_ds  -d $model_file -F "weka.filters.unsupervised.attribute.Remove -R 1" -W weka.classifiers.functions.SMO -- -M -C $C -L 0.0010 -P 1.0E-12 -N 1 -V -1 -W 1 -K "weka.classifiers.functions.supportVector.PolyKernel -C 250007 -E 1.0"

	java -Xmx$jvm_mem -classpath $weka_jar weka.classifiers.meta.FilteredClassifier -o -l "$model_file" -T $test_file -p 0 -distribution > $prediction_file # prediction on test set

	java -Xmx$jvm_mem -classpath $weka_jar weka.classifiers.meta.FilteredClassifier -o -l "$model_file" -T $train_file -p 0 -distribution > $prediction_file.train_set # prediction on the train set	
	
	# train and test on the selected features
#	java -Xmx$jvm_mem -classpath $weka_jar weka.classifiers.meta.FilteredClassifier -v -o -no-cv -t $train_file_sel  -d $model_file.sel -F "weka.filters.unsupervised.attribute.Remove -R 1" -W weka.classifiers.functions.SMO -- -M -C $C -L 0.0010 -P 1.0E-12 -N 1 -V -1 -W 1 -K "weka.classifiers.functions.supportVector.PolyKernel -C 250007 -E 1.0"

#        java -Xmx$jvm_mem -classpath $weka_jar weka.classifiers.meta.FilteredClassifier -o -l "$model_file.sel" -T $test_file_sel -p 0 -distribution > $prediction_file.sel

done 
