#! /bin/bash

# script to get the means of the psyc and child features to help mean normalize later on

rm -r ../../features/means_stds
mkdir ../../features/means_stds

for dirs in ../../features/concatenated_features/*
do
	mkdir ../../features/means_stds/$(basename $dirs)

	for files in $dirs/*
	do
		num_lines=$(cut -d' ' -f6 $files |  grep -v '^$' | wc -l)
		head -n $num_lines $files | sed 's/--undefined--/-99/g' > ../../features/means_stds/$(basename $dirs)/$(basename $files).matrix
		python get_feat_mean_var.py ../../features/means_stds/$(basename $dirs)/$(basename $files).matrix ../../features/means_stds/$(basename $dirs)/$(basename $files).mean_std
	
	done
done
